<?php
/**
 * MessengerApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Мессенджер
 *
 * API Мессенджера - набор методов для получения списка чатов пользователя на Авито, получения сообщений в чате, отправки сообщения в чат и другие Через API Мессенджера можно организовать интеграцию между мессенджером Авито и сторонней системой в обе стороны  **Авито API для бизнеса предоставляется согласно [Условиям использования](https://api.avito.ru/docs/public/APITermsOfServiceV1.pdf).**
 *
 * OpenAPI spec version: 1
 * Contact: supportautoload@avito.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * MessengerApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MessengerApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for chatRead
     *
     * Прочитать чат.
     *
     */
    public function testChatRead()
    {
    }

    /**
     * Test case for deleteMessage
     *
     * Удаление сообщения.
     *
     */
    public function testDeleteMessage()
    {
    }

    /**
     * Test case for getChatById
     *
     * Получение информации по чату.
     *
     */
    public function testGetChatById()
    {
    }

    /**
     * Test case for getChats
     *
     * Получение информации по чатам.
     *
     */
    public function testGetChats()
    {
    }

    /**
     * Test case for getMessages
     *
     * Получение списка сообщений.
     *
     */
    public function testGetMessages()
    {
    }

    /**
     * Test case for getMessagesV2
     *
     * Получение списка сообщений V2.
     *
     */
    public function testGetMessagesV2()
    {
    }

    /**
     * Test case for postBlacklist
     *
     * Добавление пользователя в blacklist.
     *
     */
    public function testPostBlacklist()
    {
    }

    /**
     * Test case for postSendMessage
     *
     * Отправление сообщения.
     *
     */
    public function testPostSendMessage()
    {
    }

    /**
     * Test case for postWebhook
     *
     * Включение уведомлений (webhooks).
     *
     */
    public function testPostWebhook()
    {
    }

    /**
     * Test case for postWebhookUnsubscribe
     *
     * Отключение уведомлений (webhooks).
     *
     */
    public function testPostWebhookUnsubscribe()
    {
    }

    /**
     * Test case for postWebhookV2
     *
     * Включение уведомлений V2 (webhooks).
     *
     */
    public function testPostWebhookV2()
    {
    }
}
